import Head from "next/head";
import { signIn } from "next-auth/react";
import { Button, Divider, Input } from "@components/index";
import { AuthLayout } from "@layout/index";
import { useForm, SubmitHandler } from "react-hook-form";

interface IFormInputs {
  email: string;
  password: string;
}

export default function Login() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IFormInputs>();
  const onSubmit: SubmitHandler<IFormInputs> = (data) => console.log(data);

  const singInUser = ({
    redirectProvider,
  }: {
    redirectProvider: "google" | "github";
  }) => {
    signIn(redirectProvider, {
      callbackUrl: "http://localhost:3000/workspaces",
    });
  };

  return (
    <>
      <Head>
        <title>Login | Slack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthLayout
        h1="Sign in to Slack"
        p={
          <p className="text-slate-900 text-lg leading-7 mb-8 text-center max-w-2xl">
            We suggest using the <strong>email address you use at work.</strong>
          </p>
        }
        href="/auth/register"
        pRecording="New to slack?"
        linkText="Create an account"
      >
        <form className="w-96" onSubmit={handleSubmit(onSubmit)}>
          <Button
            text="Sign In With Google"
            src="/assets/googleIcon.svg"
            alt="google icon"
            onClick={() => singInUser({ redirectProvider: "google" })}
            className="text-sky-600 border-sky-600 mb-4"
          />

          <Button
            text="Sign In With Github"
            src="/assets/githubIcon.svg"
            alt="github icon"
            onClick={() => singInUser({ redirectProvider: "github" })}
            className="text-slate-900 border-slate-900"
          />

          <Divider text="OR" />

          <Input
            type="email"
            placeholder="name@slack.com"
            className="mb-4"
            error={errors.email ? true : false}
            errorMessage={errors.email?.message}
            {...register("email", {
              required: "Please fill in your email.",
              pattern: {
                value: /\S+@\S+\.\S+/,
                message: "Invalid email address",
              },
            })}
          />

          <Input
            type="password"
            className="mb-4"
            placeholder="password"
            error={errors.password ? true : false}
            errorMessage={errors.password?.message}
            {...register("password", {
              required: "Password is required",
            })}
          />

          <Button
            text="Sign In With Email"
            className="text-white bg-fuchsia-900 border-none"
            type="submit"
          />
        </form>
      </AuthLayout>
    </>
  );
}
