import { HomePageLayout } from "@layout/index";
import { NextApiRequest } from "next";
import { getServerSession } from "next-auth";
import { useSession } from "next-auth/react";
import Head from "next/head";

export default function Home(): JSX.Element {
  const { data: session } = useSession();
  console.log({ session });
  return (
    <>
      <Head>
        <title>Home | Slack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-fuchsia-900">
        <HomePageLayout />
      </div>
    </>
  );
}

export async function getServerSideProps({ req }: { req: NextApiRequest }) {
  const session = await getServerSession(req);

  if (session)
    return {
      redirect: {
        destination: "/workspaces",
        permanent: true,
      },
    };

  return {
    props: {},
  };
}
