import { HomePageLayout } from "@layout/index";
import { NextApiRequest, NextApiResponse } from "next";
import { getServerSession } from "next-auth";
import Head from "next/head";

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Home | Slack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-fuchsia-900">
        <HomePageLayout />
      </div>
    </>
  );
}

export async function getServerSideProps({
  req,
  res,
}: {
  req: NextApiRequest;
  res: NextApiResponse<any>;
}) {
  const session = await getServerSession(req, res, {});

  if (session)
    return {
      redirect: {
        destination: "/workspaces",
      },
    };

  return {
    props: {
      session,
    },
  };
}
